In [1]:
import numpy as np
zero_vector = np.zeros(3)
print(zero_vector)
#0으로 초기화된 1차원의 vector생성

[0. 0. 0.]


In [2]:
zero_matrix = np.zeros((4,3))
print(zero_matrix)
#2차원 배열이 생성된다.

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np
my_array = np.zeros(15).reshape(3,5)
my_array += 4
print(my_array)

[[4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4.]]
