In [5]:
import math
import numpy as np
math.sqrt(2)
# sqrt는 제곱근 출력

#math.sqrt([2,3,4])사용시 에러가 뜸
#기본 파이썬에서 제공해주는 math모듈로는 이러한 기능을 수행할 수 없기 때문에
#numpy의 다양한 수학적이거나 통계적인 기능을 활용하면 편리하다. 
np.sqrt([2,3,4])


array([1.41421356, 1.73205081, 2.        ])

In [5]:
import numpy as np
ary = np.array([[1,2],[3,4]])
print(ary.transpose())
#num배열은 전치 행렬로 변환하는 transport메소드가 있어야 가능하다.
#전치행렬은 행과 열을 교환하여 얻어지는 행렬을 말하며 대각선을 기준으로 위치를 바꾼 행렬을 의미

[[1 3]
 [2 4]]


In [6]:
import numpy as np
x = np.array([1,2,3])
y = np.array([4,5,6])
z = x+y
print(z)

[5 7 9]


In [7]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(X[1]) #x배열의 인덱스 1번의 내용을 출력
print(X[:,1]) #각 1차원 배열의 1번의 내용을 출력

[4 5 6]
[2 5 8]


In [9]:
a = np.array([10,20,30,40,50,60,70])
i = [1,3,5]
print(a[i])
# 1,3,5인덱스에 조장된 값이 출력

[20 40 60]
