In [3]:
import pandas as pd
import numpy as np

In [6]:
sr = pd.Series([17000,18000,1000,5000],
               index=["피자","치킨","콜라","맥주"])
print('시리즈 출력 :')
print('-'*15)
print(sr)

시리즈 출력 :
---------------
피자    17000
치킨    18000
콜라     1000
맥주     5000
dtype: int64


In [11]:
data = [
    ['1000','steve','90.72'],
    ['1001','james','78.09'],
    ['1002','doyeon','98.43'],
    ['1003','jane','64.19'],
    ['1004','tony','81.30'],
    ['1005','pilwoong','99.14'],
]

df = pd.DataFrame(data, columns=['학번','이름','점수'])
print(df.head(3))

     학번      이름     점수
0  1000   steve  90.72
1  1001   james  78.09
2  1002  doyeon  98.43


In [15]:
mat = np.eye(3) #대각선으로 1 나타내기
print(mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
n=2
range = np.array(np.arange(30).reshape(5,6))
print(range)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [22]:
mat = np.array([[1,2,3],[4,5,6]])

mat1 = mat[:,1]
print(mat1)

[2 5]
