In [19]:
x = np.array([1,3,5,7,9,11]).reshape(3,2)
print(x)
#reshape()메소드를 추가하면 numpy의 2차원 배열을 원하는 모양으로 생성

y = np.ones(([3,4]))
print(y)
#numpy형식의 2차원 배열을 1의 값들로 채우려면 다음과 같이 실행

x = np.array([[1,3,5],[2,4,6]])
print(x[1]) #[2,4,6] 출력
print(x[1].mean()) #4.0 출력
print(x.mean()) # 3.5 출력
print(x.shape) #(2,3) 출력
#첫 번째 print문은 2차원 배열의 첫 번째 원소인 1차원 배열
#두 번째 print문은 첫 번째 1차원 배열에 저장된 원소들의 평균값을 실수형태로 출력
#세 번째 print문은 x배열 전체의 원소들의 평균값을 구해 출력
#네 번째 print문은 x배열의 모양(형식)을 출력

#list1 = ([1,11],[2,12],[3,13])
#print(list1[1][1])
#list1의 [2,12]칸의 12를 출력

#list2 = [[1,11],[2,12],[3,13]]
#print(list2[:][1])
#print(list2[:,1]) 에러발생

#import numpy as np
#list1 = [[1,11],[2,12],[3,13]]
#np_ary = np.array(list1)
#print(np_ary[:,1])
#2차원 리스트를 우선 numpy의 배열 형식으로 변환 후 print(np_ary[:,1])과 같이 실행

import numpy as np
#list1 = [[1,11],[2,12],[3,13]]
#print(np.array(list1[:,1]))
#라고 입력시 numpy로 변환하기 전 슬라이스를 했기때문
list1 = np.array([[1,11],[2,12],[3,13]])
print(list1[:,1])

import numpy as np
list1 = [[1,11],[2,12],[3,13]]
print(np.array(list1[:][1]))
# 결과값 [ 2 12]



[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[2 4 6]
4.0
3.5
(2, 3)
[11 12 13]
[ 2 12]
